module.exports = {
  collectCoverageFrom: [
    "**/*.js",
    "!**/node_modules/**",
    "!**/pg.service.js/**",
    "!**/master_models/**",
    "!**/queries/**",
    "!**/config/**",
    "!**/migrations/**",
    "!**/secretsList.js/**",
    "!**/data/**",
    "!**/test/**",
    "!**/index.js",
    "!**/master.service.js",
    "!**/jest.config.js",
    "!**/app_models/**",
    "!**/utilities/**",
    "!**/redis/**",
    "!**/db.js/**",
    "!**/server.js/**",
  ],
  coverageReporters: ["html", "text", "text-summary", "cobertura", "lcov"],
  testMatch: ["**/*.test.js"],
  // globalSetup: './test/setup.js',
  coveragePathIgnorePatterns: ["node_modules", "coverage", "jest", "test"],
  coverageThreshold: {
    global: {
      // branches: 80,
      // functions: 80,
      // lines: 80,
      // statements: -10,
    },
  },
};
